using Homework_6.Model;

namespace Homework_6.Service
{
    public class StudentService
    {
        private List<Student> _studentsList;
        private int _autoGeneratedID;

        public StudentService()
        {
            _studentsList = new List<Student>();
            _autoGeneratedID = 1;
        }
        public int AddStudent(StudentRequestDTO student)
        {
            var newStudent = new Student
            {
                Id = _autoGeneratedID++,
                Name = student.Name,
                Age = student.Age,
                Grade = student.Grade
            };
            _studentsList.Add(newStudent);
            return newStudent.Id;
        }
        public Student GetStudentById(int id)
        {
            return _studentsList.FirstOrDefault(s => s.Id == id);
        }
        public List<Student> GetAllStudents()
        {
            return _studentsList;
        }

        public void UpdateStudent(int id, Student newStudent)
        {
            var student = _studentsList.FirstOrDefault(s => s.Id == id);
            if (student != null)
            {
                student.Name = newStudent.Name;
                student.Age = newStudent.Age;
                student.Grade = newStudent.Grade;
            }
        }
        public int GetTotalStudents()
        {
            return _studentsList.Count;
        }
        public bool DeleteStudent(int id)
        {
            var student = _studentsList.FirstOrDefault(s => s.Id == id);
            if (student != null)
            {
                _studentsList.Remove(student);
                return true;
            }
            return false;
        }
    }
}
